// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2v5xqhCQDkAEIwzHDVK1rKro3JRruaMs',
    appId: '1:12563084290:web:52b022a1a1ba75fc9fe31b',
    messagingSenderId: '12563084290',
    projectId: 'finance-ai-dev-dd3fe',
    authDomain: 'finance-ai-dev-dd3fe.firebaseapp.com',
    storageBucket: 'finance-ai-dev-dd3fe.firebasestorage.app',
    measurementId: 'G-XZV7PDL1KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfeCn6UWP86GPs-EBRmNjLIsT_luqOZM',
    appId: '1:12563084290:android:df468c3c3b6e47889fe31b',
    messagingSenderId: '12563084290',
    projectId: 'finance-ai-dev-dd3fe',
    storageBucket: 'finance-ai-dev-dd3fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYz4N2HfautCiYHtCWxo7XWtvSMQXo0Y',
    appId: '1:12563084290:ios:3bf7614a7d4056149fe31b',
    messagingSenderId: '12563084290',
    projectId: 'finance-ai-dev-dd3fe',
    storageBucket: 'finance-ai-dev-dd3fe.firebasestorage.app',
    iosBundleId: 'com.trl.miniFinan',
  );
}
